#!/bin/sh
MSG_FILE="$1"
SOURCE="${2:-}"
if [ "$SOURCE" = "merge" ]; then
  CURRENT_MSG="$(git log -1 --pretty=%B HEAD@{1})"
  if [ -n "$(printf "%s" "$CURRENT_MSG" | tr -d '[:space:]')" ]; then
    printf "%s\n" "$CURRENT_MSG" > "$MSG_FILE"
  fi
fi
